{% set name = "pygypsy" %}
{% set version = "0.2.9" %}
{% set sha256 = "a0f4e0444fda2e3205f91468c2f765ad5bdc303538668bbafa7e12f5cbf21941" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  skip: true  # [not py27]
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - pygypsy = pygypsy.scripts.cli:cli

requirements:
  build:
    - python
    - setuptools
    - toolchain
    - numpy x.x
    - numpy >=1.11
    - cython 0.25.1
  run:
    - python
    - click >=6.6
    - numpy x.x
    - numpy >=1.11
    - pandas >=0.18.1
    - matplotlib >=1.5.2
    - colorlog >=2.7.0
    - jsonschema >=2.5.1
    - boto3 >=1.4.1
    - boto >=2.43.0

test:
  commands:
    - pygypsy -h

about:
  home: http://github.com/tesera/pygypsy
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Forestry Growth and Yield Projection SYstem for python'

  description: |
    pygypsy is a python implementation of the Growth and Yield Projection
    SYstem. It has compiled extensions and links against numpy.
  doc_url: http://pygypsy.readthedocs.io/
  dev_url: https://github.com/tesera/pygypsy

extra:
  recipe-maintainers:
    - jo-tham
    - whyvez
    - kayakwest
