travis:
  secure:
    BINSTAR_TOKEN: TTcxxx+g0RQM8ktcMsSWMfDyE6iFGNpm068PEafJxXAJ12+LA0HgRotrjVHHE/7gXFZ+YNTigceKScsyj2qlvh927s9AH/Ox8olH4HnSJS6ZQ7HbLy7LRSZvrC9qFtgvTmWNOkZ/9akpFtyP0q1CvYCCmPuf9SPMslWpD7wKHAQ9bcWp1LoqMKvz6F0EMdy20b0ASkC+S1XR4G99h/ERaJpSM2CEVr0vrltSQepKR7hmxGCMvkgWjGFB6pf5ZeEGeen5x6VZQXimRh/ByWbr+bN6NcVdzi+4+gVbsEJGkpp7TVM/KXjFejQDsT96f7YNgP9kgt5Si8SSzMfVwKzDteCPpgyI5QQA8DkcZ/MoChMCBEtglYbaEWz7wIu0tU6Ii9GXvwheTuEw61ZnRUewu+NejujbNZ6tZJVFvIStoL09WO/ybClX+cmeK58NoSaHQEXOUX8VBgVJumRvqVAv/PHc4FP1Bl8AjOAXyQZBGKONkM/b0uZlh8VDH28476drW2q0o0RQpZIKmhYrrqh4FlJtO1g+rFqL+0es6kyKzHb15JePXel14l6ViTBdeH6iWhcWHk45X0WN0Tks3soyvcFatuAWksIgKpTiwB3MH77bH3hnQuV2dYUbks+wL8ovRPEgFm3+3dvhJ4QGAaaPPUz/19Jj2ewRzbXpg4UwU+w=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
