travis:
  secure:
    BINSTAR_TOKEN: UCo1yz26AyNwMuwXOFfLILMBCc8Fo5wXZRyTZ5PU71MNykxZS7+wpo/mHS2ADo9r+KkqgEgqhWoJuuM2ML0p22n2jKUH8P9dz8VoeUchwWdKuiS0Qse7o45dvEpRT+81CN1sgf3FScsa52GTow2AHox0/lMyOBI+p593OCyoCowQfkdi0zV36gAihXtgedjzGI2Xuiz2LSfnVXbzJRUCEKdE6gWP9EOQbMMX3Gn3Ttsv4+Qepjl6Zlzf+k0ys68GRMqwiZLXsjE24EZmsr/ddq40BD596mv1m87e/A70sjBWCk20CcmLEJPgHd5KdWZ5RJbcPU0uF1fIBmSlu6K9x2yCH6n31gb+KP2QtI6kn81O/FZvW1Ihw2elVmRaeSbDA8fAmk9FWXe42Kj4e9tVOqwt9AwuTwiDXRbOWw0GEnxy+LxcJWj+ohgT/PvWURx0g0euzUbYzanTwKQX37y1g2XojJW53Ot8bQquI6uStshW5LK0Y7LWsKnl/4FwMWb7VO6iRDycQ8DMX6RQLF8pDjSpEBKvOWKtbQX2QKzw3NT3tvYDiUXWTNrh3vpHCIHd9iOMcPBHiLLWm+Btjh2db01nbNqZVFrZZtHFjqEvMG4nARNJoNYE23rASY1hTz5vBrh+qwjI/Kekcr4NiNfB7vmIM8S7K6MWcU2NgZOnCJs=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
